import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fullstack Developer | MERN Stack, React Native, PHP & Laravel',
  description: 'Professional Fullstack Developer specializing in MERN Stack, React Native, PHP and Laravel. Let\'s build something amazing together.',
  keywords: 'Fullstack Developer, MERN Stack, React Native, PHP, Laravel, Next.js, Web Development',
  authors: [{ name: 'Your Name' }],
  openGraph: {
    title: 'Fullstack Developer Portfolio',
    description: 'MERN Stack, React Native, PHP & Laravel Developer',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Fullstack Developer Portfolio',
    description: 'MERN Stack, React Native, PHP & Laravel Developer',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}







// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
